# Generated by Django 4.0 on 2022-04-11 20:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('backend', '0004_meetinguserlist'),
    ]

    operations = [
        migrations.AddField(
            model_name='meeting',
            name='block_turns',
            field=models.BooleanField(default=False),
        ),
    ]
